### ISSUE TITLE
Will it support this kind of format?

### ISSUE THREAD

**Issue by carry0987** [splashsky/modello#1]
For example,
in html file:
```html
<h1>{$value}</h1>
```
and it will do this:
```php
<?php echo $value; ?>
```

**Comment by splashsky** [comment]
Yes, however, syntactically you'd want to type `[@value]`, such as `<h1>[@value]</h1>` and it will work exactly as you described. :+1: 

If you have any issues using the class, please reply here and I'll get it fixed and get examples up as soon as I'm able. :smiley:

**Comment by carry0987** [comment]
I'm very glad to hear that,this template is awesome,I ask for 
```php
{$value} 
```
is just because I will use this code in my html,I will change my code to use your template,this is my project:
[Messageboard](
https://github.com/carry0987/MessageBoard-Beta)

**Comment by splashsky** [comment]
It's awesome to hear you've found a use for my bit of code! You've given me an idea to update this class to be able to accept new Regex patterns for matching tags. I'll put up examples of usage today. 👍

**Comment by carry0987** [comment]
I'm a newbie in php,but if anything I can help,please let me know because I want to learn about it~

**Comment by splashsky** [comment]
Absolutely! You're more than welcome to fork the project, add some code and submit a pull request 😃

**Comment by carry0987** [comment]
I will fork it !
So...may I have some work to do?
I have never made template yet,so maybe I need some tips?
ex: database connect,insert data...etc

**Comment by splashsky** [comment]
For the most part, the Modello class simply opens a text file, reads it, and parses that text data and then outputs it. A couple improvements that could be made are more semantic batch-loading for multiple template files, and the ability for the user to adjust the Regex pattern as they see fit.

**Comment by carry0987** [comment]
I will make a little demo to test it, thanks !

**Comment by carry0987** [comment]
I think I have some idea about it:

Echo :
html
```html
<!--{$value}-->
```
PHP
```php
<?php echo $value; ?>
```

Loop:
```html
<!--{loop $a $b $c}-->
Some HTML you want to loop
<!--{/loop}-->
```
PHP
```php
<?php
foreach($a as $b => $c) {
Some HTML you want to loop
}
?>

**Comment by carry0987** [comment]
I think I have some idea about it:

echo function
html
```html
<span>{$value}</span>
```
PHP
```php
<span><?php echo $value; ?></span>
```

if function
html
```html
<!--{if expr1}-->
	statement1
<!--{elseif expr2}-->
	statement2
<!--{else}-->
	statement3
<!--{/if}-->
```
PHP
```php
<?php
if(expr1) {
    statement1
} elseif(expr2) {
    statement2
} else {
    statement3
}
?>
```

loop function (no key)
html
```html
<!--{loop $array $value}-->
	Some HTML you want to loop,like
      <span>username</span>
<!--{/loop}-->
```
PHP
```php
<?php
foreach($array as $value) {
	Some HTML you want to loop,like
      <span>username</span>
}
?>
```

loop function (use key)
html
```html
<!--{loop $array $key $value}-->
Some HTML
<!--{/loop}-->
```
PHP
```php
<?php
foreach($array as key => $value) {
Some HTML
}
?>
```

**Comment by carry0987** [comment]
I am coding parser.php,wait for me~

**Comment by splashsky** [comment]
These ideas are pretty amazing; I'd love to incorporate some of them into Modello. I've been rewriting the class a bit since this issue was opened and I'm hoping to commit some progress to a branch soon. 👍

**Comment by carry0987** [comment]
I have wrote some regex to try to make my idea come true,but I don't know how could it work...
I will paste it here to show you my immature code~

**Comment by splashsky** [comment]
Moved the suggestion for control structures to a new Issue, closing this one :smile:
