### ISSUE TITLE
Add Control Structures to Modello

### ISSUE THREAD

**Issue by splashsky** [splashsky/modello#3]
I think I have some idea about it:

echo function
html
```html
<span>{$value}</span>
```
PHP
```php
<span><?php echo $value; ?></span>
```

if function
html
```html
<!--{if expr1}-->
	statement1
<!--{elseif expr2}-->
	statement2
<!--{else}-->
	statement3
<!--{/if}-->
```
PHP
```php
<?php
if(expr1) {
    statement1
} elseif(expr2) {
    statement2
} else {
    statement3
}
?>
```

loop function (no key)
html
```html
<!--{loop $array $value}-->
	Some HTML you want to loop,like
      <span>username</span>
<!--{/loop}-->
```
PHP
```php
<?php
foreach($array as $value) {
	Some HTML you want to loop,like
      <span>username</span>
}
?>
```

loop function (use key)
html
```html
<!--{loop $array $key $value}-->
Some HTML
<!--{/loop}-->
```
PHP
```php
<?php
foreach($array as key => $value) {
Some HTML
}
?>
```

_Originally posted by @carry0987 in https://github.com/splashsky/modello/issues/1#issuecomment-373682256_

**Comment by carry0987** [comment]
Here is my PHP-Template-Engine project, take a look : [Link](https://github.com/carry0987/PHP-Template-Engine)

**Comment by splashsky** [comment]
Big thanks to @carry0987! For v1.1.0 I've added basic support for if-else control structures with some simple syntax. Take a look at the v1.1.0-alpha release!

**Comment by carry0987** [comment]
Congratulations !
